#Ejecicio 5
#PIDE POR TERMINAL QUE INGRESEN UN NUMERO ENTERO,
#SINO ES ENTERO, ENTONCES IMPRIME UN MENSAJE DE ERROR DICIENDO QUE NO SE ACEPTAN DECIMALES
#ADICIONAL, SI EL NUMERO ES MULTIPLO DE 3, IMPRIME LA PALABRA "FIZZ"
#SI EL NUMERO ES MULTIPLO DE 5, IMPRIME LA PALABRA "BUZZ"
#Y SI ES MULTIPLO DE 15, IMPRIME LA PALABRA "FIZZBUZZ"

num=int(input("Enter a number: "))

if num % 3 == 0:
    print("FIZZ")
if num % 5 == 0:
    print("BUZZ")
if num % 15 == 0:
    print("FIZZBUZZ")